- OgreMain/include/OgreRenderQueue.h
Based on what @darksylinc  wrote in https://forums.ogre3d.org/viewtopic.php?f=2&t=94628#p543341
> Docs: point out render order if DisableSort is used

- OgreMain/include/OgreRoot.h
- OgreMain/include/OgreSceneManager.h
- OgreMain/src/OgreSceneManager.cpp
This change is a backport of `commit:13b016f`.
Currently, these changes are important to me, but upgrading to v2-1 is difficult, so please merge those changes.
see also : https://github.com/OGRECave/ogre-next/issues/55
*This branch has been tested.*
> Backport of `commit:13b016f` into v2-0.

- OgreMain/include/OgreManualObject2.h
- OgreMain/src/OgreManualObject2.cpp
See also: [https://forums.ogre3d.org/viewtopic.php?f=25&t=95544]()
> Add support to convert a manual object in a mesh (v2)

- Components/Hlms/Pbs/CMakeLists.txt
- Components/Hlms/Unlit/CMakeLists.txt
> Fix *.inl files aren't installed by CMake

- Docs/src/SettingUpOgre/SettingUpOgre.md
- Docs/src/SettingUpOgre/SettingUpOgre_macOS.md
It's not too comprehensive, but it's a start!
> Add build instructions for macOS

- Components/Hlms/Pbs/include/OgreHlmsPbs.h
- Components/Hlms/Pbs/src/OgreHlmsPbs.cpp
- Samples/2.0/ApiUsage/ShadowMapDebugging/ShadowMapDebuggingGameState.cpp
- Samples/Media/Hlms/Pbs/Any/ShadowMapping_piece_ps.any
> Added support for PCF 5x5 and 6x6 shadow filter

- .github/workflows/main.yml
> Fix doxygen publish

- Docs/src/SettingUpOgre/SettingUpOgre_macOS.md
* Add CXXFLAGS build flags to macos docs
* Use Make's `-j2` flag in macos
> Refine macOS build guide

- OgreMain/src/OgreScriptTranslator.cpp
> Print the errornous pixel format

- RenderSystems/Vulkan/CMakeLists.txt
https://github.com/OGRECave/ogre-next/issues/143
> RenderSystems/Vulkan on UNIX should link against X11-xcb

- OgreMain/src/OgrePlatformInformation.cpp
> OgrePlatformInformation.cpp: fixed build on MIPS architecture

- Samples/2.0/Common/src/GraphicsSystem.cpp
This was breaking the Release build of Samples.
> Add missing include file to Samples

- Samples/2.0/Tutorials/Tutorial_Terrain/include/Terra/Hlms/OgreHlmsTerra.h
- Samples/Media/Hlms/Terra/Any/800.PixelShader_piece_ps.any
Fix #72 and increase HLMS Terra user-customizability.
> Fix Terra normal maps issue and increase its modularity

- OgreMain/include/Animation/OgreBone.h
Add missing functions to get tag points from a bone.
> Get tag point from bone.

- OgreMain/src/OSX/OgreConfigDialog.mm
- OgreMain/src/OSX/OgreErrorDialog.mm
Most of these changes are just replacing a constant defined in Apple's headers with a newer one that does the same thing.
> Fix some Mac-specific deprecation warnings.

- RenderSystems/Direct3D11/src/Windowing/WIN32/OgreD3D11WindowHwnd.cpp
- RenderSystems/GL3Plus/src/windowing/win32/OgreWin32Window.cpp
@darksylinc,
If you need support for new Win64 systems, these changes are necessary.
> Replaced deprecate functions in Win64

- CMakeLists.txt
removing unused code in cmake file due to outdated cmake version
> removing unused code in cmake file due to outdated cmake version

- Samples/Media/Hlms/Pbs/Any/Main/800.VertexShader_piece_vs.any
This is to address issue #373.
> Add vertex shader code for accurate non-uniform-scaled normals

- RenderSystems/GL3Plus/src/windowing/win32/OgreWin32GLSupport.cpp
Attributes should be assigned in pairs.
Here it was probably forgotten.
> +bugfix attributes should be assigned in pairs

- OgreMain/include/OgreItem.h
- OgreMain/src/OgreItem.cpp
Item::clone has been documented but unimplemented for years.
> remove Item::clone

- Samples/Media/Hlms/Pbs/Any/Main/200.BRDFs_piece_ps.any
As I said on forum:
https://forums.ogre3d.org/viewtopic.php?p=554454#p554454
this was crashing in GL3+ for me on Debian.
> fix space between _h and (

- CMakeLists.txt
See https://forums.ogre3d.org/viewtopic.php?t=97086
See https://developercommunity.visualstudio.com/t/msvc-incorrectly-defines-cplusplus/139261
> Tell MSVC to report a newer cplusplus

- Samples/2.0/Common/include/CameraController.h
- Samples/2.0/Tutorials/Tutorial_Terrain/src/Tutorial_TerrainGameState.cpp
I find it better. At least I can now move around w/o yawning :yawning_face: 
Happy 400 PRs BTW. :tada:
> Tutorial Terrain faster camera speed etc

- Samples/2.0/Common/include/CameraController.h
- Samples/2.0/Common/src/CameraController.cpp
:stuck_out_tongue_winking_eye:
> fix spelling

- .github/workflows/main.yml
removed duplicated line into main.yml
> removed duplicated line into main.yml

- OgreMain/CMakeLists.txt
Remove old msvc 10  configuration
Clean cmake
> Clean  CMakeLists.txt

- Samples/2.0/CMakeLists.txt
The path can be constructed optimally. Good if you use FetchContent.
> Use of OGRE_TEMPLATES_DIR

- OgreMain/CMakeLists.txt
> fix the failure to use the OgreNext name in Xcode project

- Samples/2.0/Tutorials/Tutorial_Hlms01_Customization/Tutorial_Hlms01_Customization.h
- Samples/2.0/Tutorials/Tutorial_Hlms02_CustomizationPerObj/Tutorial_Hlms02_CustomizationPerObj.h
- Samples/2.0/Tutorials/Tutorial_Hlms03_AlwaysOnTopA/Tutorial_Hlms03_AlwaysOnTopA.h
- Samples/2.0/Tutorials/Tutorial_Hlms04_AlwaysOnTopB/Tutorial_Hlms04_AlwaysOnTopB.h
- Samples/2.0/Tutorials/Tutorial_Hlms05_CustomizationPerObjData/Tutorial_Hlms05_CustomizationPerObjData.h
> fix compile error when building the 5 Hlms tutorials for macOS or iOS

- CMakeLists.txt
- Components/Property/CMakeLists.txt
- Components/Property/include/OgreProperty.h
- Components/Property/include/OgrePropertyPrerequisites.h
- Components/Property/src/OgreProperty.cpp
- Tests/Components/Property/src/PropertyTests.cpp
Just made it compilable. Took code snippets from the Ogre 1 repository. Hope it works.
> Component Property adjusted

- Components/Paging/CMakeLists.txt
- Components/Paging/include/OgrePage.h
- Components/Paging/include/OgrePageContent.h
- Components/Paging/include/OgrePageContentCollection.h
- Components/Paging/include/OgrePageContentCollectionFactory.h
- Components/Paging/include/OgrePageContentFactory.h
- Components/Paging/include/OgrePageManager.h
- Components/Paging/include/OgrePageStrategy.h
- Components/Paging/include/OgrePagedWorld.h
- Components/Paging/include/OgrePagedWorldSection.h
- Components/Paging/include/OgrePagingPrerequisites.h
- Components/Paging/src/OgrePagedWorldSection.cpp
Just made it compilable. Hope it works.
> Component Paging adjusted
